"""Added new tables

Revision ID: 85881f2072a7
Revises: c84ba0c895ef
Create Date: 2023-11-04 21:43:40.091991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85881f2072a7'
down_revision: Union[str, None] = 'c84ba0c895ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('group_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
