"""Your message here describing the change

Revision ID: c84ba0c895ef
Revises: 6fd5efaeb5b0
Create Date: 2023-10-31 00:12:38.237768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c84ba0c895ef'
down_revision: Union[str, None] = '6fd5efaeb5b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('message', 'recipient_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('recipient_id', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
